# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "build Production and upload to App Store"
  lane :prod do
    build_app(scheme: "OursReader",configuration: "Debug", export_method:"app-store",xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(username: "cliffchan1993@hotmail.com")
  end

end


