# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "update version number"
  lane :update_version do
    buildNumber = increment_version_number

    UI.success("Update version number to #{buildNumber}")
  end

  desc "update build number"
  lane :update_build_number do
    buildNumber = increment_build_number

    UI.success("Update build number to #{buildNumber}")
  end

  desc "build Production and upload to TestFlight"
  lane :prod do
    build_app(
      scheme: "OursReader",
      configuration: "Release",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )

    # Authentication is supplied by the local/CI fastlane session or API key.
    # Do not hard-code a personal Apple ID in the repository.
    upload_to_testflight
  end

end
